adback_db:
  image: mysql:5.7
  volumes:
   - ./db_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: wordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress
  ports:
   - "3308:3306"

wordpress:
  links:
   - adback_db
  image: wordpress:latest
  volumes:
   - ./../adback-solution-to-adblock:/var/www/html/wp-content/plugins/adback-solution-to-adblock
  ports:
   - "80:80"
  environment:
   WORDPRESS_DB_HOST: adback_db:3306
   WORDPRESS_DB_PASSWORD: wordpress
